export const defaultLanguageLabels = {
  RESERVEPARKING: "RESERVE PARKING NOW!",
  MANAGEMYBOOKING: "My Account",
  SELECTLOCATION: "Select Parking Location",
  SELECTEVENT: "Select Event",
  ARRIVE: "Arrive",
  TIME: "Time",
  DEPART: "Depart",
  GETRATE: "Get Rates",
  NOEVENTSTHISTIME: "No events at this time",
  CHOOSEEVENT: "Choose parking by event",
  CHOOSEPRESET: "Choose parking by preset time",
  CHOOSEPASSTYPE: "Choose a Pass",
  NOPRESETTIME: "No presets at this time",
  PURCHASEPASS: "Purchase Pass",
  REPEATPURCHASESIMPLEWIDGETMESSAGE:
    "You have selected repeat for a location where it is not activated. Please continue",
  REPEATPURCHASESIMPLEWIDGETEMPTYMESSAGE:
    "You have not made a previous booking, return to home screen to make a booking then use repeat purchase next time",
  SHOWMSEASONPARKING: "Show me season parking",
  NOSEASONTICKET: "No season ticket",
  SELECTSEASONTICKETDATE: "Select start date",
  CHOOSESEASONTICKET: "Select season ticket",
  PARKRIGHTNOW: "Park Right Now",
  MULTIUSEPASSLBL: "I want a multi-use or season pass",
  NOFIXEDACCESSPASSES: "No passes at this time",
  ARRIVALDATE: "My Arrival Date",
  DEPARTUREDATE: "My Departure Date",
  TIMEDTITLE: "Hourly Parking",
  EVENTTITLE: "Event Parking",
  PASSESTITLE: "Parking Passes",
};
